version: "3.7"
services:
  nginx:
    image: nginx
    ports:
      - "8000:80"
      - "3000:443"
    restart: always
  mysql:
    image: mysql
    networks:
      - db-network
    environment:
      MYSQL_ROOT_PASSWORD: kurdyumov
    ports:
      - "3306:3306"
  pma:
    image: phpmyadmin/phpmyadmin
    networks:
      - db-network
    ports:
      - "8080:80"
    environment:
      PMA_HOST: mysql
    depends_on:
      - mysql
networks:
  db-network:
